image: maven:3.6.0-jdk-11

variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - pages
  - deploy

cache:
  paths:
    - .m2/repository
    - target/
build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS compile package"
  artifacts:
    paths:
      - "target/*.jar"
pages:
  stage: pages
  script:
    - "mvn $MAVEN_CLI_OPTS dokka:dokka"
    - "mv ./target/dokka public/"
  artifacts:
    paths:
      - "public"
deploy:
  stage: deploy
  script:
    - "mvn $MAVEN_CLI_OPTS deploy"
  only:
    - master
    - develop
