image: maven:3.3.9-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/
build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS compile"
pages:
  stage: pages
  script:
    - "mvn javadoc:javadoc"
    - "mv target/site/apidoc public/"
  artifacts:
    paths:
      - "public"
deploy:
  image: maven:3.3.9-jdk-8
  script:
    - "mvn deploy"
  only:
    - master
    - develop
